name: "Test"

on:

  push:
    branches: ["master"]
  pull_request_target:
    types: [ "opened", "reopened", "synchronize" ]
  
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable.yml
